### ISSUE TITLE
svg remounted on every render

### ISSUE THREAD

**Issue by istarkov** [JoshRosenstein/emotion-icons#3]
This is because of this line https://github.com/JoshRosenstein/emotion-icons/blob/master/src/createIcon.js#L48 new component created on every render.

This causes serious performance issues in my app  ;-) I will provide a PR

And thank you for this icon pack!!!

**Comment by JoshRosenstein** [comment]
@istarkov  Thanks for reporting this, and sorry for not seeing this earlier. I will look into this and create some tests. thank you

**Comment by JoshRosenstein** [comment]
[![Edit emotion-icons-svg-remount-bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/50mxl14wrx)

Quick comparison between new and old createIcon function. Will be creating a PR shortly

**Comment by JoshRosenstein** [comment]
@istarkov - v.0.0.9 if available with this fix. thank you for reporting
