### ISSUE TITLE
Support for emotion 10

### ISSUE THREAD

**Issue by Betree** [JoshRosenstein/emotion-icons#6]
Emotion 10 has been released and `react-emotion` deprecated in favor of `@emotion/styled`.

See the migration guide here: https://emotion.sh/docs/migrating-to-emotion-10

**Comment by JoshRosenstein** [comment]
Sorry, been away from from a bit. This should roll out soon as v1.0

**Comment by JoshRosenstein** [comment]
@Betree - should be good to go. please let me know if you have any issues
